server.port=8891

spring.application.name=config-server
spring.profiles.active=native
spring.cloud.config.server.native.search-locations=file:./config-repo,file:../config-repo,file:./backend/config-repo,file:d:/EShoppingZone/config-repo

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always
